# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94eab6449f556ba93b60ffda8bcad646f56e0a9569e7a872f969341e169bb331680e8c8b6bcfd09708e898dd009d66a76c0fb2f2de792e59a40cc6034ec56be6

test:
  secret_key_base: 330c65d1b52d4961eb0b908feb4f4e2e7dfca7eb2e964b4ca0c12a2169732d2162e6edb2a7463fc18b29ece77a32848fd8709905c224ef08aae614394e44c3a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
